USE SHINDEH;
DROP TABLE IF EXISTS FILE;
CREATE TABLE FILE(
ID INT NOT NULL AUTO_INCREMENT,
TAG VARCHAR(500),
TOKEN VARCHAR(500),
URL VARCHAR(500),
ROLE  VARCHAR(100),
USER_ID INT,
PRIMARY KEY(ID),
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);